import { Dimensions, StyleSheet } from 'react-native';
const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 15,
    paddingTop: 58,
    backgroundColor: "#f8f8f8",
    borderBottomWidth: 1,
    borderColor: "#ddd",
  },
  iconContainer: {
    flexDirection: "row",
    gap: 15,
  },
  headerTitle: {
    fontFamily: "Prociono",
    fontSize: 28,
    color: "#010101",
  },
  icon: {
    padding: 5,
  },
  heroSection: {
    alignItems: "center",
    padding: 20,
    backgroundColor: "#f8f8f8",
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
  },
  heroImage: {
    width: '100%',
    height: 180,
    resizeMode: 'contain',
    marginBottom: 15,
    borderRadius: 10,
  },
  heroTitle: {
    fontSize: 59,
    fontFamily: "Montserrat",
    fontWeight: "800",
    color: "#000000",
    letterSpacing: -2.97,
    marginBottom: 16,
  },
  heroSubtitle: {
    fontSize: 24,
    fontFamily: "Poppins",
    fontWeight: "500",
    color: "#000000",
    marginBottom: 10,
    textAlign: "center",
  },
  donateImageContainer: {
    alignItems: "center",
    padding: 20,
  },
  donateImage: {
    width: '100%',
    height: 400,
    // resizeMode: 'contain',
    borderRadius: 10,
  },
  separatorContainer: {
    alignItems: "center",
    paddingHorizontal: 20,
  },
  separatorImage: {
    width: '100%',
    height: 50,
    resizeMode: 'contain',
  },
  donationCardsSection: {
    padding: 20,
  },
  sectionTitle: {
    fontSize: 40,
    fontFamily: "Montserrat",
    fontWeight: "800",
    color: "#010101",
    marginBottom: 20,
  },
  newsletter: {
    padding: 20,
    alignItems: "center",
    marginTop: 30,
  },
  newsletterTitle: {
    fontSize: 40,
    fontFamily: "Montserrat",
    fontWeight: "800",
    color: "#000000",
    textAlign: "center",
    marginBottom: 33,
  },
  newsletterSubtitle: {
    fontSize: 24,
    fontFamily: "Poppins",
    fontWeight: "500",
    color: "#000000",
    textAlign: "center",
    marginBottom: 32,
  },
  content: {
    padding: 20,
  },
  title: {
    fontSize: 40,
    fontFamily: "Montserrat",
    fontWeight: "800",
    color: "#000000",
    marginBottom: 16,
  },
  subtitle: {
    fontSize: 24,
    fontFamily: "Poppins",
    fontWeight: "500",
    color: "#000000",
    marginBottom: 20,
  },
  mainImage: {
    width: '100%',
    height: 200,
    resizeMode: 'cover',
  },
  donateCard: {
    width: "100%",
    aspectRatio: 0.913,
    padding: 20,
    position: "relative",
    borderRadius: 10,
    overflow: "hidden",
    backgroundColor: "#f8f8f8",
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  donateBackground: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 10,
  },
  donateSection: {
    padding: 20,
    marginTop: 10,
  },
  donateTitle: {
    fontSize: 40,
    fontFamily: "Montserrat",
    fontWeight: "800",
    color: "#fff",
    marginTop: 110,
  },
  joinButton: {
    width: "100%",
    maxWidth: 269,
    borderWidth: 1,
    borderColor: "#000000",
    padding: 26,
    alignItems: "center",
    borderRadius: 10,
    backgroundColor: "#f8f8f8",
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
});